name: package

on:
  push:
    paths:
      - 'package.json'
      - 'README.md'
      - 'color.css'
      - '.github/workflows/package.yml'

jobs:
  publish-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
